version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ["./wait.sh"]
    ports:
      - "8000:8000"

  db:
    image: mysql/mysql-server:8.0.23
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: k1ngk0ng
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro