# Generated by Django 3.1 on 2022-08-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todo_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
